version: '3.7'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=!Password
      - POSTGRES_DB=django_main_db_dev
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A main worker -l info
    volumes:
      - ./main:/main
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data:
